[testServer]

#info using Tasneems broker host (mq vm)

BROKER_HOST = 100.67.124.17
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
EXCHANGE_TYPE = topic
AUTO_DELETE = false

